image : microsoft/aspnetcore-build:latest
stages:
  - compile
  - test
  - build
compile:
  stage: compile
  script:
    - 'dotnet restore'
    - 'dotnet build'
test:
  stage: test
  script:
    - 'dotnet test MovieAPIUnitTest/MovieAPIUnitTest.csproj'
build:
  stage: build
  script:
    - 'dotnet publish moviecruiser -c Release'
  artifacts:
    expire_in: 1 month
    paths:
      - moviecruiser/bin/Release/netcoreapp2.0/publish/